spring:
  application:
    name: product
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ # 多个以逗号隔开，eureka即是服务端，也是客户端

